### ISSUE TITLE
Allow for different convergence criteria in PLS

### ISSUE THREAD

**Issue by M-E-Steiner** [M-E-Steiner/cSEM#42]
Allow for different convergence criteria in order make comparisons across other packages and software possible.

**Comment by FloSchuberth** [comment]
I have written the function (Flo branch 00_new) but I have not placed it in the estimatorWeights function, since I have no time to test it. However the function is there. Just the arguments need to be added to the list and the function has to be put in the right place. So the issue can almost be closed ;)

**Comment by M-E-Steiner** [comment]
fixed
